version: '3.8'

services:
  survival_server:
    image: app_server:latest
    build:
      target: survival_server
      context: .
    env_file:
      - .env
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    extra_hosts:
      - "host.docker.internal:host-gateway"
